### ISSUE TITLE
How to generate a new canera_path for new view synthesis?

### ISSUE THREAD

**Issue by visonpon** [Kai-46/nerfplusplus#13]
Hi @Kai-46, could you share how to generate a continuous and proper camera_path for the new view synthesis

**Comment by Xianjin111** [comment]
Hi~Do you know how to generate the new camera_path? Thank you very much.

**Comment by visonpon** [comment]
@Xianjin111, just take a look at [here](def interpolate_waypoints(wpRs, wpts, steps=25):)

**Comment by Xianjin111** [comment]
> @Xianjin111, just take a look at[ here](https://github.com/intel-isl/StableViewSynthesis/blob/797bc9bc0c3150bcc40be0eec971dc710f71a1ff/data/create_custom_track.py#L399)

Thank you so much!
