### ISSUE TITLE
About run_colmap

### ISSUE THREAD

**Issue by zrw97402** [Kai-46/nerfplusplus#14]
Thanks for your work firstly. I am now working on my outdoor datasets and have some bad results in previous NeRF methods.  I want to try on your code but I fail to build the dataset as the form of yours because of the run_colmap.py.  I wonder where the __install__/bin/colmap is under the colmap/build directory.  I just know how to use the cmake to compile colmap and cannot find the above path . Could you give me some advice?

**Comment by Kai-46** [comment]
If you are on unix-like system, you can use "which colmap" to find the path.

**Comment by zrw97402** [comment]
It works for my datasets, thank you very much!

**Comment by jly0810** [comment]
> 它可以作为我的数据集，非常感谢你！



Hello, may I ask if you can run your own dataset? I will use run_ Colmap encountered some errors while training to obtain its own dataset
