### ISSUE TITLE
No validation data provided for Truck scene in Preprocessed Trucks and Temples zip

### ISSUE THREAD

**Issue by avani17101** [Kai-46/nerfplusplus#17]
There is validation data provided for other scenes except the truck. Is it intentional or by a mistake? Can you please provide validation data of the Truck scene as well

**Comment by Kai-46** [comment]
Hi @avani17101 , please take a look at this closed issue: https://github.com/Kai-46/nerfplusplus/issues/2

**Comment by avani17101** [comment]
thanks @Kai-46  https://github.com/Kai-46/nerfplusplus/issues/2 worked
