### ISSUE TITLE
about inverted sphere parameterization

### ISSUE THREAD

**Issue by bring728** [Kai-46/nerfplusplus#19]
To do volume rendering, we need to get x', y', z'. 
![image](https://user-images.githubusercontent.com/24850969/105345706-eb887280-5c27-11eb-806c-fe3246604a88.png)

And in the paper, in order to find x', y', z', it is said to be obtained by rotating point a of the figure.

If you just divide x, y, z by r, isn't it x', y', z'? Why do I have to get it as hard as a picture? Am I misunderstanding something?

**Comment by Kai-46** [comment]
For distant points, (x, y, z) can be huge, leading to numeric issues.

**Comment by bring728** [comment]
Oh, we should also think about numeric issues! And,

![image](https://user-images.githubusercontent.com/24850969/105435119-1a422f80-5ca0-11eb-9d42-dfbda508cedb.png)

looking at the code, when sampling the background, we don't know the coordinates of x,y,z, so you have to rotate point (a) to get x',y',z'! When sampling, only 1/r is known... I understood. Thank you!
