### ISSUE TITLE
there is no 'validation' dir in 'tanks_and_temples/tat_training_Truck'

### ISSUE THREAD

**Issue by piaozhx** [Kai-46/nerfplusplus#2]

**Comment by Kai-46** [comment]
actually, in the preprocessed data, i always set validation set to be the same as the test set. hence you can create a symbolic link by "ln -s ./test validation" inside the tat_training_Truck directory.

**Comment by Kai-46** [comment]
They are different scenes from the tanks and temples dataset: https://www.tanksandtemples.org/.

**Comment by sararoma95** [comment]
thanks
