### ISSUE TITLE
About shape-radiance ambiguity

### ISSUE THREAD

**Issue by 07hyx06** [Kai-46/nerfplusplus#20]
Thanks for your work! 

I have some questions about the solution you construct to demonstrate the shape-radiance ambiguity in Paragraph 2 of Section 3:

> To illustrate this ambiguity, imagine that for a given scene we represent the geometry as a unit
sphere. In other words, let us fix NeRF’s opacity field to be 1 at the surface of the unit sphere,
and 0 elsewhere. Then, for each pixel in each training image, we intersect a ray through that pixel
with the sphere, and define the radiance value at the intersection point (and along the ray direction)
to be the color of that pixel. This artificially constructed solution is a valid NeRF reconstruction
that perfectly fits the input images.

1, Does it means that the opacity field inside the unit sphere is fixed to 0?
2, If only the opacity field at the surface be 1, the integral in Eq.(2) should be zero, since there are at most only two non-zero points along the ray.
3, Or you let $dt$(the step size of the numerical integration) to 1?

So I cannot figure out why this is a valid solution...Can you help me?

**Comment by Kai-46** [comment]
It would be nice if you can think that the opacity field is 1 in a tiny area around the surface; or in other words, imagine the surface has certain tiny thickness in 3D.
