### ISSUE TITLE
run_colmap json files

### ISSUE THREAD

**Issue by grgkopanas** [Kai-46/nerfplusplus#22]
Hi,

Thanks for sharing your code. I am running the colmap script on my own data and it produces json files but all the examples scenes you give have the camera parameters and poses in txt files. Is there a utility to convert jsons to txt files or the main train script can understand both?

George

**Comment by Kai-46** [comment]
The txt files contain the flattened matrices, just like the json files, which is somewhat straightforward to implement.

**Comment by grgkopanas** [comment]
Thanks, that makes sense 👍
