### ISSUE TITLE
split_size error when trainning

### ISSUE THREAD

**Issue by Xianjin111** [Kai-46/nerfplusplus#24]
Thank you for your perfect work. When I train on my own dataset, there exists error as follows:
<img width="1041" alt="截屏2021-03-17 上午1 18 58" src="https://user-images.githubusercontent.com/46471572/111352096-cf043600-86be-11eb-8eca-191575c26044.png">

Could you please help me deal with it. Thanks so much!

**Comment by dwangxxx** [comment]
> Thank you for your perfect work. When I train on my own dataset, there exists error as follows:
> <img alt="截屏2021-03-17 上午1 18 58" width="1041" src="https://user-images.githubusercontent.com/46471572/111352096-cf043600-86be-11eb-8eca-191575c26044.png">
> 
> Could you please help me deal with it. Thanks so much!

你好，我想问下你这个问题是怎么解决的呀？是不是因为输入图片的尺寸不一致呀？

**Comment by kam1107** [comment]
It's probably caused by the mismatch in image shapes. All images are reshaped to have 3 channels in RaySamplerSingleImage(). Check if your inputs have more than 3.
