### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by yggs1401** [Kai-46/nerfplusplus#3]
Hello!

First of all, nice job! I was wondering how can we preprocess new data and make our own dataset with generated poses, intrinsics. Thanks in advance!

**Comment by Kai-46** [comment]
you can follow the descriptions on the readme to convert your poses to the format suitable for this repo.

**Comment by yggs1401** [comment]
I was having problems generating those files using COLMAP. Mind if you can help with a tip :).

I've managed to reconstruct the mesh based on my images, but I don't know how to continue from here. I think that I need to export the sparse folder as .txt, but then I don't really know what information do I need to make the poses.txt and intrinsic.txt

Thank you and stay safe!

**Comment by Kai-46** [comment]
I do have some scripts for doing this. I'll clean them a bit for easier access before getting back to you.

**Comment by yggs1401** [comment]
I'm glad to hear that! Thank you very much and I'm waiting for them.

**Comment by Kai-46** [comment]
I just added some scripts to generate poses from COLMAP to the repo. You can see the description about how to use them at the bottom of the readme. Let me know if you encounter any issues.

**Comment by yggs1401** [comment]
Thank you! I will try them.

**Comment by yggs1401** [comment]
One more question than everything is fine. The intrinsics of the camera is the same for all the datasets? I read in COLMAP docs if the pictures were taken by the same objective, we need a single camera. I think that's why all your datasets share the same intrinsics.
But if we get a new set of pictures taken with another objective (my phone's camera), how can I get the new intrinsics for it?

Thank you and sorry for the silly questions!

**Comment by Kai-46** [comment]
No worries. COLMAP SfM estimates poses, as well as intrinsics from images. You will see the estimated intrinsics and poses after you run the script 'colmap_runner/run_colmap.py'.

**Comment by yggs1401** [comment]
Thank you very much for your help! Keep up the good work! :)
