### ISSUE TITLE
what LICESE is for nerfplusplus ? 

### ISSUE THREAD

**Issue by hirokic5** [Kai-46/nerfplusplus#39]
Thanks for a great repository !!!

I'd like to use those nerfplusplus codes for daily task for job if possible.
So, what kind of license is expected in this repository ?

**Comment by Kai-46** [comment]
Hi @hirokic5 , thanks for your interest in our work. I just added the BSD 2-Clause license to the repo: [link](https://github.com/Kai-46/nerfplusplus/blob/ebf2f3e75fd6c5dfc8c9d0b533800daaf17bd95f/LICENSE#L1). 

Cheers,
Kai

**Comment by hirokic5** [comment]
Thanks you so much !!
