### ISSUE TITLE
Question about the background net

### ISSUE THREAD

**Issue by MultiPath** [Kai-46/nerfplusplus#4]
Hi, amazing work! I have a small question about the model:
At L119:
https://github.com/Kai-46/nerfplusplus/blob/770e584f6d35b910655a2bcaf328f9123eb14545/ddp_model.py#L119

why the "dists" is inversed distance, instead of the real distance? It seems wrong in volume rendering? or Am I missing something?
Thanks so much!

**Comment by Kai-46** [comment]
We use inverted sphere parametrization for the background (see section 4 of our arXiv preprint). Because of the re-parametrization, the volumetric rendering integral is now w.r.t. 1/r (inverse radius).

**Comment by MultiPath** [comment]
I understood the inverted sphere parameterization. However, when computing the integral, shouldn't sigma still multiply the real distance?
![image](https://user-images.githubusercontent.com/5780274/96665058-0cd47c80-1322-11eb-8222-9f539922210b.png)

**Comment by MultiPath** [comment]
> I understood the inverted sphere parameterization. However, when computing the integral, shouldn't sigma still multiply the real distance?
> ![image](https://user-images.githubusercontent.com/5780274/96665058-0cd47c80-1322-11eb-8222-9f539922210b.png)

Even if we use "u=1/t" to replace t in the integral, it seems still not equivalent... 
Sorry I am bad at math, just wondering how this was computed exactly.

**Comment by Kai-46** [comment]
You are right. The t^2 term is implicitly absorbed into the sigma_out.

**Comment by MultiPath** [comment]
Ok, thanks for reply!! I think it is better to note at somewhere in the paper or code. 
Also, what is your opinion to stick to the physical expression or not? Maybe the way you learn sigma_out is more stable?

**Comment by Kai-46** [comment]
Can you clarify a bit? You mean 'dividing sigma_out by t^2'?

**Comment by MultiPath** [comment]
If you do variable replacement, you should multiply sigma_out by t^2 if you keep the original physical meaning of "density".
However, if you define the density itself in an inverted space, maybe the current formulation is fine, and in fact your results are great! Just think maybe you can clarify in the paper/code.

**Comment by MultiPath** [comment]
> Can you clarify a bit? You mean 'dividing sigma_out by t^2'?

And yes. not sure which way is in fact better in practise.

**Comment by Kai-46** [comment]
Note that t^2 can be very big for unbounded scenes, hence it can cause numeric issue when you are dealing with very faraway background, e.g., horizons.

**Comment by MultiPath** [comment]
But it is inside the ``exp`` function, which will simply making the term close to 0. I don't think it will cause numeric issue.

**Comment by Kai-46** [comment]
Sorry, I'm confused. Isn't d(1/t)=-1/t^2 dt, which means you would have a -1/t^2 term outside the exp?

**Comment by MultiPath** [comment]
![image](https://user-images.githubusercontent.com/5780274/96678275-65fed900-133f-11eb-99fd-657e02d5bbbf.png)
Your exp is outside of the integral, and exp's speed to converge to 0 is way faster than 1/t^2 i think

**Comment by Kai-46** [comment]
First, note that there're two integrals in term (iii); for the outside integral in term (iii), you see the term 1/t^2 as well. Second, I think we are confusing notations here. Let us first agree that t>1 is Euclidean distance. Now let r=1/t \in (0, 1). We have dr=-1/t^2 dt, which means dt=-t^2 dr = -1/r^2 dr. When r approaches zero, you are dividing sigma by r^2 that also approaches zero. This is not numeric stable?

**Comment by MultiPath** [comment]
the outside integral multiplied with the exp part, which will make the whole thing close to 0.

**Comment by Kai-46** [comment]
Got you. But how would you avoid dividing by zero in implementation, specifically the case r=1/t approaches zero? With some careful numeric implementation, I guess it might be doable, though.

**Comment by MultiPath** [comment]
yeah. I just wonder will the choice of modeling do affect the results. 
Also, sorry for asking, I am a bit confused by your code ``depth2pts_outside``. 
Could you confirm that when you sample from 0 ~ 1, you first find the sphere intersection, and sample radius r starting from the intersection (1) until infinite (0). And then find the actual intersection on the ray?

**Comment by Kai-46** [comment]
Yes, please see our arXiv preprint for text description.

**Comment by kwea123** [comment]
In my opinion it's similar to NDC in NeRF, in NDC the distance is not real distance either, but they still use the same formula to do volume rendering. So I think the interpretation of sigma can change depending on the context. For example we can consider that in NeRF++, the sigma is real density inside the unit sphere, but "real density times `r`" outside the unit sphere.

**Comment by kwea123** [comment]
However I believe that there is some bug here:
https://github.com/Kai-46/nerfplusplus/blob/57920483846bbab7708f9d30f797f42962b6d6e1/ddp_model.py#L128

The `bg_z_vals` is inverse radius, so here you're computing the expectance of the inverse radius, which doesn't correspond to distance at all. In my opinion you should use the `depth_real` coming from `depth2pts_outside`.
