### ISSUE TITLE
LPIPS version

### ISSUE THREAD

**Issue by Shubhendu-Jena** [Kai-46/nerfplusplus#42]
Hi, 

Thanks for the great work. Could you please tell me what version of LPIPS was used to obtain the results as stated in the paper? 
i.e. AlexNet, VGG or SqueezeNet?

Thanks in advance

**Comment by Kai-46** [comment]
VGG, if I remembered it correctly.

**Comment by Shubhendu-Jena** [comment]
Thank you!
