### ISSUE TITLE
Run on cumstom data

### ISSUE THREAD

**Issue by Derry-Xing** [Kai-46/nerfplusplus#43]
I have run colmap on my own data. Then I convert it to json format by running extract_sfm.py. THen I run normalize_cam_dict.py to get the normalized json. But when I am training the model, it requires intrinsics.txt and other files that are not generated in my pipeline, How to run your code on our custom dataset?

**Comment by Kai-46** [comment]
You could simply flatten the matrices `K` and` C2W=np.linalg.inv(W2C)` in the json file to text files.

**Comment by joeyw1030** [comment]
你好 你可以运行自己的数据集了吗

**Comment by Derry-Xing** [comment]
> 你好 你可以运行自己的数据集了吗

I haven't tried it.

**Comment by i-nkrumah** [comment]
Have you been able to run on a custom dataset?
