### ISSUE TITLE
how to extract a mesh from nerf++ models?

### ISSUE THREAD

**Issue by menglongyue** [Kai-46/nerfplusplus#45]
expecting for some advice about extracting mesh from nerf++ model!!!

**Comment by ZZy129326999** [comment]
> expecting for some advice about extracting mesh from nerf++ model!!!

Hello. Dear the expert. I very want to query you for some issues about NeRF chunkfiles. Can you give me your email? How are the chunk files in MegaNeRF generated? Thank you very much!

**Comment by menglongyue** [comment]
> 
the training chunks? or the rendering data? my email is huangquanjin24@gmail.com
