### ISSUE TITLE
Optimize per-image autoexposure

### ISSUE THREAD

**Issue by kwea123** [Kai-46/nerfplusplus#9]
Where is the code and do you have an explanation of how it works? Thanks.

**Comment by Kai-46** [comment]
The basic idea is to optimize a per-image scale and offset parameter, as can be seen [here](https://github.com/Kai-46/nerfplusplus/blob/acc089a449866fd71bc26975ca9ba67d1abfbb5a/ddp_model.py#L169). This functionality is experimental, and not fully tested, though.
